name: Semantic Release

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    environment: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup python for test Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish to pypi
      if: steps.release.outputs.released == 'true'
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        uv build
        uv publish
